Repository CCP2003/Competetive-Coding, pull requests merged in 2022-10, with the labels that each got.

#2 LeetCode Hard Question
  LeetCode 154. Find Minimum in Rotated Sorted Array II
Labels: Hacktober Fest, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST

#3 LC7. Reverse Integer
  LC7. Reverse Integer
Labels: "HACKTOBERFEST-ACCEPTED"

#4 LC14. Longest Common Prefix
  LC14. Longest Common Prefix
Labels: HACKTOBERFEST-ACCEPTED

#6 LC7. Reverse Integer
  LC7. Reverse Integer
Labels: HACKTOBERFEST-ACCEPTED

#5 Create LC14. Longest Common Prefix
  LC14. Longest Common Prefix
Labels: Hacktober Fest, HACKTOBERFEST-ACCEPTED

#7 Leetcode 557 solution
  Leetcode 557
Labels: HACKTOBERFEST-ACCEPTED

#8 CodeChef Sum of Product 1
  CodeChef Sum of Product 1
Labels: HACKTOBERFEST-ACCEPTED

#9 LC98. Validate Binary Search Tree
  LC98. Validate Binary Search Tree
Labels: HACKTOBERFEST-ACCEPTED

#10 LC5. Longest Palindromic Substring
  LC5. Longest Palindromic Substring
Labels: HACKTOBERFEST-ACCEPTED

#11 LC3. Longest Substring Without ...
  LC3. Longest Substring Without Repeating Characters
Labels: HACKTOBERFEST-ACCEPTED

#12 LC114. Flatten Binary Tree to Linked List
  LC114. Flatten Binary Tree to Linked List
Labels: HACKTOBERFEST-ACCEPTED

#14 HackeRank Exceptional Server
  HackeRank Exceptional Server
Labels: HACKTOBERFEST-ACCEPTED

#16 Create LC-42. Trapping Rain Water.java
  LC-42. Trapping Rain Water.java
Labels: HACKTOBERFEST-ACCEPTED

#19 Create LC-4 Median of two Sorted Arrays [Hard Question].java
  LC-4 Median of two Sorted Arrays [Hard Question].java
Labels: HACKTOBERFEST-ACCEPTED

#21 Create LC - 172 Factorial Trailing Zeroes[Medium Que].java
  LC - 172 Factorial Trailing Zeroes[Medium Que].java
Labels: HACKTOBERFEST-ACCEPTED

#18 Searching in 2D matrix
  Searching in 2D efficiently
Labels: HACKTOBERFEST-ACCEPTED

#20 Create HackerRank Dqueue STL
  HackerRank Dqueue STL
Labels: HACKTOBERFEST-ACCEPTED

#17 Int to Roman
  Int to roman
Labels: HACKTOBERFEST-ACCEPTED
